In [1]:
import pandas as pd

In [ ]:
df = pd.read_excel(
    "./data/original(do not modify)/Personal_income_by_state(billions).xlsx",
    header=5)
df.head()

/home/kien/torch_cuda/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,GeoFIPS,GeoName,LineCode,Description,1929,1930,1931,1932,1933,1934,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,00000,United States,1.0,Personal income (millions of dollars),85151,76394,65531,50162,47114,53967,...,15884741.0,16658962.0,17514402.0,18349584.0,19613059.0,21484168.0,22144814.0,23577208.0,24897613.0,26109831.2
1,00000,United States,2.0,Population (persons) 1,121769000,123075000,124038000,124839000,125580000,126372000,...,324353340.0,326608609.0,328529577.0,330226227.0,331578104.0,332100166.0,333996304.0,336755052.0,340003797.0,341784857.0
2,00000,United States,3.0,Per capita personal income (dollars) 2,699,621,528,402,375,427,...,48974.0,51006.0,53311.0,55567.0,59151.0,64692.0,66303.0,70013.0,73227.0,76393.0
3,01000,Alabama,1.0,Personal income (millions of dollars),843.2,697.5,583.7,421.9,435.6,556.3,...,190871.8,197963.8,205674.2,215151.8,230878.4,255682.3,262425.8,279484.6,295590.5,309906.4
4,01000,Alabama,2.0,Population (persons) 1,2644000,2647000,2649000,2653000,2661000,2685000,...,4931579.0,4953096.0,4977088.0,5003778.0,5032962.0,5050058.0,5076868.0,5117850.0,5163055.0,5193088.0

# Inflation

In [36]:
df = pd.read_excel(
    "../data/original(do not modify)/GDP_and_personal_income/Personal_Income_and_Outlays/Annual_T2.3.7._Percent_Change_From_Preceding_Period_in_Prices_for_Personal_Consumption_Expenditures_by_Major_Type_of_Product.xlsx",
    header=7
)
df.head()

,Line,Unnamed: 1,Unnamed: 2,1930,1931,1932,1933,1934,1935,1936,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,1,Personal consumption expenditures (PCE),DPCERV,-4.2,-10.7,-11.8,-3.6,4.5,2.5,0.9,...,1.0,1.7,2.0,1.4,1.1,4.1,6.5,3.8,2.6,2.6
1,2,Goods,DGDSRV,-5.3,-13.8,-13.8,-0.8,9.9,2.7,0.4,...,-1.6,0.3,0.8,-0.4,-0.8,4.9,8.6,1.2,-0.4,0.7
2,3,Durable goods,DDURRV,-5.9,-10.7,-11.9,-2.4,6,-0.6,0.6,...,-2.2,-2.3,-1.4,-1.0,-0.9,5.5,6.5,-0.7,-2.1,0.4
3,4,Motor vehicles and parts,DMOTRV,-3.7,-6.7,-6.2,-6.2,4.7,-1.5,0.5,...,-0.6,-1.3,0.0,0.8,1.6,11.4,11.7,0.1,-2.0,1.3
4,5,Furnishings and durable household equipment,DFDHRV,-3.8,-11.2,-13.7,0.3,8.1,0.6,0.7,...,-2.7,-2.8,-1.0,0.7,0.9,5.1,9.2,-0.8,-3.1,0.8

In [37]:
df = df.drop(columns=["Line", "Unnamed: 2"])
df.head()

,Unnamed: 1,1930,1931,1932,1933,1934,1935,1936,1937,1938,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Personal consumption expenditures (PCE),-4.2,-10.7,-11.8,-3.6,4.5,2.5,0.9,3.6,-2.3,...,1.0,1.7,2.0,1.4,1.1,4.1,6.5,3.8,2.6,2.6
1,Goods,-5.3,-13.8,-13.8,-0.8,9.9,2.7,0.4,3.6,-4.1,...,-1.6,0.3,0.8,-0.4,-0.8,4.9,8.6,1.2,-0.4,0.7
2,Durable goods,-5.9,-10.7,-11.9,-2.4,6,-0.6,0.6,4.1,-0.1,...,-2.2,-2.3,-1.4,-1.0,-0.9,5.5,6.5,-0.7,-2.1,0.4
3,Motor vehicles and parts,-3.7,-6.7,-6.2,-6.2,4.7,-1.5,0.5,2.5,4,...,-0.6,-1.3,0.0,0.8,1.6,11.4,11.7,0.1,-2.0,1.3
4,Furnishings and durable household equipment,-3.8,-11.2,-13.7,0.3,8.1,0.6,0.7,6.7,-1.8,...,-2.7,-2.8,-1.0,0.7,0.9,5.1,9.2,-0.8,-3.1,0.8

In [ ]:
df.rename(columns={"Unnamed: 1": "category"})
df.head()

,Unnamed: 1,1930,1931,1932,1933,1934,1935,1936,1937,1938,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Personal consumption expenditures (PCE),-4.2,-10.7,-11.8,-3.6,4.5,2.5,0.9,3.6,-2.3,...,1.0,1.7,2.0,1.4,1.1,4.1,6.5,3.8,2.6,2.6
1,Goods,-5.3,-13.8,-13.8,-0.8,9.9,2.7,0.4,3.6,-4.1,...,-1.6,0.3,0.8,-0.4,-0.8,4.9,8.6,1.2,-0.4,0.7
2,Durable goods,-5.9,-10.7,-11.9,-2.4,6,-0.6,0.6,4.1,-0.1,...,-2.2,-2.3,-1.4,-1.0,-0.9,5.5,6.5,-0.7,-2.1,0.4
3,Motor vehicles and parts,-3.7,-6.7,-6.2,-6.2,4.7,-1.5,0.5,2.5,4,...,-0.6,-1.3,0.0,0.8,1.6,11.4,11.7,0.1,-2.0,1.3
4,Furnishings and durable household equipment,-3.8,-11.2,-13.7,0.3,8.1,0.6,0.7,6.7,-1.8,...,-2.7,-2.8,-1.0,0.7,0.9,5.1,9.2,-0.8,-3.1,0.8

In [18]:
df = df.dropna(thresh=10)

In [19]:
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [category, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
Index: []

[0 rows x 97 columns]

In [28]:
df.describe()

,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,...,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,3.716129,4.148387,4.287097,2.874194,2.193548,2.019355,1.800000,1.777419,1.909677,1.345161,...,0.164516,1.703226,2.012903,0.893548,0.032258,5.387097,7.680645,2.932258,1.806452,2.045161
std,2.129960,2.858539,3.658574,2.892515,2.900912,2.355762,1.496217,1.701707,2.285951,2.340205,...,3.248646,3.108749,2.966338,1.899638,3.809146,6.307125,6.365345,3.882816,2.871577,1.967374
min,-1.200000,-6.500000,-8.400000,-7.500000,-9.100000,-5.300000,-2.100000,-4.200000,-7.100000,-8.400000,...,-11.400000,-3.700000,-3.300000,-4.000000,-15.000000,0.500000,0.500000,-10.200000,-5.400000,-4.900000
25%,2.800000,3.800000,3.850000,2.150000,1.200000,0.900000,1.050000,1.150000,1.650000,0.700000,...,-0.950000,0.350000,0.650000,0.150000,-0.750000,2.900000,5.100000,2.300000,0.050000,0.850000
50%,4.200000,4.400000,4.600000,3.300000,2.800000,2.600000,2.000000,2.200000,2.300000,1.800000,...,1.200000,1.600000,1.900000,1.400000,1.200000,3.700000,5.500000,4.000000,2.600000,2.600000
75%,4.750000,5.050000,5.050000,4.200000,3.600000,3.500000,2.750000,2.800000,2.950000,2.800000,...,2.150000,2.400000,2.450000,2.250000,2.050000,5.000000,8.900000,4.950000,3.650000,3.250000
max,8.100000,9.300000,14.500000,8.400000,7.500000,5.600000,4.600000,4.000000,6.800000,4.300000,...,4.600000,12.800000,13.500000,3.400000,3.300000,33.100000,32.300000,8.800000,6.800000,5.800000

In [31]:
df.isna().any(axis=1).sum()

np.int64(0)

In [35]:
df.category

AttributeError: 'DataFrame' object has no attribute 'category'

In [33]:
df

,category,1930,1931,1932,1933,1934,1935,1936,1937,1938,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Personal consumption expenditures (PCE),-4.2,-10.7,-11.8,-3.6,4.5,2.5,0.9,3.6,-2.3,...,1.0,1.7,2.0,1.4,1.1,4.1,6.5,3.8,2.6,2.6
1,Goods,-5.3,-13.8,-13.8,-0.8,9.9,2.7,0.4,3.6,-4.1,...,-1.6,0.3,0.8,-0.4,-0.8,4.9,8.6,1.2,-0.4,0.7
2,Durable goods,-5.9,-10.7,-11.9,-2.4,6,-0.6,0.6,4.1,-0.1,...,-2.2,-2.3,-1.4,-1.0,-0.9,5.5,6.5,-0.7,-2.1,0.4
3,Motor vehicles and parts,-3.7,-6.7,-6.2,-6.2,4.7,-1.5,0.5,2.5,4,...,-0.6,-1.3,0.0,0.8,1.6,11.4,11.7,0.1,-2.0,1.3
4,Furnishings and durable household equipment,-3.8,-11.2,-13.7,0.3,8.1,0.6,0.7,6.7,-1.8,...,-2.7,-2.8,-1.0,0.7,0.9,5.1,9.2,-0.8,-3.1,0.8
5,Recreational goods and vehicles,-16.7,-20.7,-17.8,-6.7,3.7,-1,-1.1,2.5,-0.4,...,-4.6,-3.7,-3.3,-4.0,-4.3,1.5,0.5,-3.1,-2.1,-1.1
6,Other durable goods,-1.8,-4.5,-10.1,0.3,3.8,-1.9,2.1,0.9,-3.3,...,-0.9,-1.3,-1.9,-2.3,-2.8,0.5,1.9,2.3,-0.6,0.9
7,Nondurable goods,-5.2,-14.5,-14.3,-0.5,10.6,3.4,0.4,3.5,-4.9,...,-1.3,1.6,1.9,-0.1,-0.7,4.6,9.9,2.3,0.5,0.8
8,Food and beverages purchased for off-premi...,-6.5,-19.3,-18.2,0.5,12.4,7.9,0.2,3.1,-7.6,...,-1.0,-0.1,0.5,1.0,3.3,3.1,10.3,5.0,1.3,1.9
9,Clothing and footwear,-4.5,-12.6,-17.9,1.9,15.9,-1.8,0.1,5.3,-2.4,...,-0.3,-0.6,0.1,-1.3,-5.1,2.1,5.2,2.5,0.7,-0.1
10,Gasoline and other energy goods,-3.3,-11.1,-2.4,-2.1,5.5,-0.9,2.7,2,-1.8,...,-11.4,12.8,13.5,-3.5,-15.0,33.1,32.3,-10.2,-5.4,-4.9
11,Other nondurable goods,-3.5,-4.7,-5.5,-5,2.5,-0.1,-0.5,3.5,-1.6,...,1.2,1.0,0.5,0.4,0.9,0.9,4.7,4.1,1.3,1.7
12,Services,-2.9,-7,-9.7,-6.3,-1.3,2.2,1.6,3.7,0.1,...,2.3,2.4,2.6,2.3,2.0,3.7,5.5,5.1,4.1,3.5
13,Household consumption expenditures (for serv...,-2.8,-7,-9.8,-6.4,-1.6,2.3,1.6,3.6,0.2,...,2.2,2.4,2.7,2.3,2.1,3.5,5.2,4.9,4.0,3.6
14,Housing and utilities,-2.7,-5.2,-9.3,-9.1,-7.6,0.3,1.6,3.7,2.5,...,2.9,3.4,3.1,3.0,2.7,2.9,6.7,7.0,5.2,4.1
15,Health care,0.3,-7,-11.9,-1.5,3.7,5.8,2.1,2.7,2,...,1.2,1.5,1.9,1.8,2.5,2.9,2.4,2.3,2.7,2.7
16,Transportation services,-0.8,-5,-7.7,-5.7,2,2.2,-0.6,-0.6,0.7,...,0.8,1.2,2.1,2.0,-0.9,4.7,11.1,7.2,2.5,3.3
17,Recreation services,-1.9,-4.5,-4.8,-5.7,0.7,1.4,1.9,3.7,1.8,...,2.4,2.8,2.1,2.0,2.2,3.0,5.4,5.1,3.6,3.7
18,Food services and accommodations,-6.1,-13.7,-15.6,-3.3,7.6,7.5,0.2,3.5,-4.7,...,2.6,2.1,2.3,2.8,2.0,5.5,7.8,6.2,3.4,3.1
19,Financial services and insurance,-2.3,-9.1,-11,-4.6,3.5,4.3,4.5,4.4,-2.4,...,4.6,5.1,5.4,2.5,1.2,5.9,5.2,4.3,6.8,5.8
20,Other services,-3.5,-7.3,-8,-4.5,1.5,1.1,1.6,5,-0.7,...,1.1,0.4,1.7,1.2,1.9,2.0,3.5,4.0,2.8,2.5
21,Final consumption expenditures of nonprofit ...,-3.8,-8.6,-7.1,-3.8,5.5,0.7,2.7,5.2,-2.6,...,2.9,2.5,1.3,2.7,0.7,8.0,11.2,8.8,5.8,2.7
22,Gross output of nonprofit institutions\2\,.....,.....,.....,.....,.....,.....,.....,.....,.....,...,2.0,2.1,2.2,2.3,2.4,4.2,5.2,4.6,4.0,3.1
23,Less: Receipts from sales of goods and ser...,.....,.....,.....,.....,.....,.....,.....,.....,.....,...,1.6,2.0,2.4,2.2,3.0,2.8,3.1,3.1,3.3,3.2
25,PCE excluding food and energy\4\,-3.7,-8.3,-11,-4.8,2.3,1.1,1.1,4.1,-0.5,...,1.6,1.6,1.9,1.6,1.4,3.6,5.3,4.2,2.9,2.8
26,"PCE excluding food, energy, and housing\4\",-3.9,-9.1,-11.1,-3,5.9,1.3,0.8,4,-1.3,...,1.2,1.2,1.6,1.3,1.0,3.8,5.2,3.5,2.4,2.6
27,Energy goods and services\5\,-2.9,-8.6,-2.2,-1.7,3.3,-1.1,1.4,1.1,-1.6,...,-7.3,8.7,8.1,-2.2,-8.4,20.7,25.7,-5.5,-2.1,-0.3
28,PCE services excluding energy and housing,-2.9,-8.1,-9.8,-4.2,3.3,3.4,1.6,3.6,-1.3,...,2.1,2.1,2.5,2.0,1.8,4.0,5.0,4.4,3.7,3.3
29,Housing,-2.8,-5.7,-10.5,-10.2,-8.8,0.5,2.3,4.7,3.1,...,3.3,3.4,3.4,3.4,2.9,2.5,5.9,7.6,5.4,3.9
30,Market-based PCE\6\,.....,.....,.....,.....,.....,.....,.....,.....,.....,...,0.7,1.4,1.8,1.3,1.0,3.6,6.4,3.6,2.2,2.3
31,Market-based PCE excluding food and energy\6\,.....,.....,.....,.....,.....,.....,.....,.....,.....,...,1.3,1.2,1.6,1.5,1.3,2.9,5.0,4.0,2.6,2.5